# Generated by Django 3.1.12 on 2025-10-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('d', models.IntegerField()),
                ('e', models.IntegerField()),
                ('average', models.FloatField()),
                ('positive_count', models.IntegerField()),
                ('even_odd', models.JSONField()),
                ('sorted_values', models.JSONField()),
                ('warning', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
